################################### GLOBAL FLASK SETTINGS ###########################################################
# Shibboleth can manage login for you. Set to 1 to turn it on.
# A shibboleth provider must be installed and configured using the Apache configuration.
# If set to 0, local login is enabled.
USE_SHIBBOLETH: 0

# Tracy can provide you with student labor data, such as positions, departments, etc.
# If set, a Tracy Ultratime SQAlchemy provider must be installed and access allowed from this server.
# Otherwise, the local MySQL instance will provide this data.
USE_TRACY: 0

# Banner can be used as the official hiring database after administrators approve a form.
# A Banner Oracle db must be installed and access allowed from this server.
USE_BANNER: 0

# Every Flask application has a secret key.
secret_key: "123"

# The default user is the application cannot find a real user
user:
 debug: "heggens"

# If you have local-only overrides, put them in this file
override_file: "local_override.yaml"

#####################################################################################################################
################################### DATABASE CONNECTIONS ############################################################
# The local database for the application. This database must exist.
# local_override.yaml probably overrides these settings.
lsfdb:
 db_name: "test"
 password: "12345"
 username: "test"
 host: "db"

# The database for work study information, such as positions, departments, etc.
tracy:
 db_name: "UTE"
 host: "db"
 username: "tracy_user"
 password: "password"
 mssql_host: "REPLACE"
 mssql_user: "REPLACE"
 mssql_password: "REPLACE"

#####################################################################################################################
#################################### EMAILER SETTINGS ###############################################################
# Turns on the emailer system, which notifies students and supervisors of changes to work positions.
# Also enables the email templating system

USE_EMAILER: False
MAIL_SERVER: "smtp.gmail.com"   # FIXME: use smtp.gmail.com for gmail
MAIL_PORT: 465                  # FIXME: use port 465 for gmail
MAIL_USERNAME: ''               # FIXME: Provide the email of the sender
MAIL_PASSWORD: ''               # FIXME: Provide the password of the sender
REPLY_TO_ADDRESS: ''            # FIXME: Provide a reply_to address
MAIL_USE_TLS: False
MAIL_USE_SSL: True
MAIL_DEFAULT_SENDER: ''         # FIXME: Add sender email address
MAIL_OVERRIDE_ALL: ''           # FIXME: Provide a debug email address, such as a Slack channel

financial_aid:
  email: '' #FIXME: Provide an email address for Financial Aid matters
#####################################################################################################################
##################################### APPLICATION FEATURES ##########################################################

# Use the flags in this section to enable or disable features that you want included in your application.

# Provides login ito students so they can see a history of their work at the institution.
STUDENT_ACCESS: 0

# Provides an interface for students to review jobs in each department. STUDENT_ACCESS must be set to 1 for this feature.
# Feature not implemented yet.
JOB_SEARCH: 0

# Allows evaluations of the students by their supervisor(s)
STUDENT_EVALUATIONS: 0

# Allows evaluations of the supervisors by their student(s)
SUPERVISOR_EVALUATIONS: 0

# Tracks payroll. Feature not implemented yet.
PAYROLL: 0

# Allows tracking of hours. Feature not implemented yet.
TIMECARDS: 0


#####################################################################################################################
##################################### LEXICON #######################################################################

# The application will use the language provided below to describe your work study program.

# The name of your institution.
INSTITUTION: Berea College

# Path to the logo in the top left corner
LOGO_PATH: "/static/logo.png"

# The name of your work study program at your institution.
PROGRAM_NAME: Labor Program

# The terms used for hiring and firing a student.
HIRE_TERM: [hire, hiring, hired]
FIRE_TERM: [release, releasing, released]

# The terms used to describe form types.
HIRE_FORM: Labor Status Form
FIRE_FORM: Labor Release Form
OVERLOAD_FORM: Labor Overload Form
CHANGE_FORM: Labor Adjustment Form

# List the names of terms, in order. If you hire students specifically for breaks, add those too.
TERM_NAMES: [Fall, Fall Break, Winter Break, Spring, Spring Break, Summer 1, Summer 2]
