################################### GLOBAL FLASK SETTINGS ###########################################################
# Every Flask application has a secret key.
secret_key: "123"

# If you have local-only overrides, put them in this file
override_file: "local_override.yml"

# The default user is the application cannot find a real user
user:
 debug: "heggens"

# Shibboleth can manage login for you. Set to 1 to turn it on.
# A shibboleth provider must be installed and configured using the Apache configuration.
USE_SHIBBOLETH: 0

# Tracy can provide you with student labor data, such as positions, departments, etc.
# A Tracy Ultratime provider must be installed and access allowed from this server.
USE_TRACY: 0

# Banner can be used as the official hiring database after administrators approve a form.
# A Banner ERP must be installed and access allowed from this server.
USE_BANNER: 0

#####################################################################################################################
################################### DATABASE CONNECTIONS ############################################################
# The local database for the application. This database must exist
lsfdb:
 db_name: "test"
 password: "12345"
 username: "test"
 host: "db"

# The database for work study information, such as positions, departments, etc.
tracy:
 db_name: "UTE"
 host: "db"
 username: "tracy_user"
 password: "password"
 mssql_host: "REPLACE"
 mssql_user: "REPLACE"
 mssql_password: "REPLACE"

#####################################################################################################################
#################################### EMAILER SETTINGS ###############################################################

financial_aid:
  email: "finaid@berea.edu"

ALWAYS_SEND_MAIL: False
MAIL_SERVER: "smtp.gmail.com" #FIXME: use smtp.gmail.com for gmail mail.berea.edu for Berea
MAIL_PORT: 465 #: use port 465 for gmail use 25 for Berea
MAIL_USERNAME: '' #FIXME: add the email of the sender
MAIL_PASSWORD: '' #FIXME: Add the password of the sender
REPLY_TO_ADDRESS: "labor_program@berea.edu"
MAIL_USE_TLS: False
MAIL_USE_SSL: True
MAIL_DEFAULT_SENDER: '' #FIXME: Add sender email address
MAIL_OVERRIDE_ALL: "j5u6j9w6v1h0p3g1@bereacs.slack.com"

#####################################################################################################################
##################################### APPLICATION FEATURES ##########################################################

# Use the flags in this section to enable or disable features that you want included in your application.

# Provides login ito students so they can see a history of their work at the institution.
STUDENT_ACCESS: 0

# Allows evaluations of the students by their supervisor(s)
STUDENT_EVALUATIONS: 0

# Allows evaluations of the supervisors by their student(s)
SUPERVISOR_EVALUATIONS: 0

# Tracks payroll. Feature not implemented yet.
PAYROLL: 0

# Allows tracking of hours. Feature not implemented yet.
TIMECARDS: 0

# Provides an interface for students to review jobs in each department. STUDENT_ACCESS must be set to 1 for this feature.
# Feature not implemented yet.
# JOB_SEARCH: 0

# Turns on the emailer system, which notifies students and supervisors of changes to work positions.
# Also enables the email templating system.
EMAILER: 0


#####################################################################################################################
##################################### LEXICON #######################################################################

# The application will use the language provided below to describe your work study program.

# The name of your institution.
INSTITUTION: Berea College

# The name of your work study program at your institution.
PROGRAM_NAME: Labor Program

# The terms used for hiring and firing a student.
HIRE_TERM: [hire, hiring, hired]
FIRE_TERM: [release, releasing, released]

# The terms used to describe form types.
HIRE_FORM: Labor Status Form
FIRE_FORM: Labor Release Form
OVERLOAD_FORM: Labor Overload Form
CHANGE_FORM: Labor Adjustment Form

# List the names of terms, in order. If you hire students specifically for breaks, add those too.
TERM_NAMES: [Fall, Fall Break, Winter Break, Spring, Spring Break, Summer 1, Summer 2]
